version: '3.7'

services:
  db:
    image: "postgres:11.4"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      - POSTGRES_DB=appetite
      - POSTGRES_USER=appetite
      - POSTGRES_PASSWORD=TeamOnTrack
    ports:
      - "54320:5432"
  web:
    build: .
    image: appetite-backend
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_NAME=appetite
      - DB_USER=appetite
      - DB_PASSWORD=TeamOnTrack
      - DB_HOST=db
    links:
      - db
    ports:
      - "8080:8000"
volumes:
  dbdata: