# Generated by Django 2.2.6 on 2019-10-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191026_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now=True)),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now=True)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now=True)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now=True)),
        ),
        migrations.AlterField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name='venue',
            name='updated_at',
            field=models.DateTimeField(verbose_name=models.DateTimeField(auto_now=True)),
        ),
    ]
