# Generated by Django 2.2.6 on 2019-10-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191027_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='reccomended',
            field=models.BooleanField(default=False),
        ),
    ]
